# Generated by Django 5.2.6 on 2025-09-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_balance_customuser_expense_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
