# Generated by Django 5.2.6 on 2025-10-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expo_notification_token',
            field=models.CharField(blank=True, help_text='Expo push notification token for this user’s device.', max_length=255, null=True),
        ),
    ]
