# Generated by Django 5.2.6 on 2025-10-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_expo_notification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expo_notification_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='firebase_notification_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging (FCM) token for this user’s device.', max_length=255, null=True),
        ),
    ]
