# Generated by Django 5.2.6 on 2025-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='Untitled Transaction', max_length=150),
        ),
    ]
