# Generated by Django 5.2.6 on 2025-10-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_userdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
